package com.amazonaws.saas.eks.orderservice.domain.model.order;

import com.amazonaws.saas.eks.orderservice.domain.model.customer.Customer;
import com.amazonaws.saas.eks.orderservice.domain.model.enums.EntityType;
import com.amazonaws.saas.eks.orderservice.domain.model.enums.OrderStatus;
import com.amazonaws.saas.eks.orderservice.domain.model.lineitem.LineItem;
import lombok.Data;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.time.Instant;

@Data
public class Order {
    public static final String TABLE = "Order-OMN";
    private String entity = EntityType.ORDERS.getLabel();
    private String id;
    private String orderId;
    private String status = OrderStatus.PROCESSING.toString();
    private List<LineItem> lineItems = new ArrayList<>();
    private Customer customer;
    private double totalAmount;
    private Instant created;
    private Instant modified;

    @DynamoDbPartitionKey
    public String getEntity() {
        return entity;
    }

    @DynamoDbSortKey
    public String getId() {
        return id;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    public Instant getCreated() {
        return created;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getModified() {
        return modified;
    }
}
