apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 708224731803.dkr.ecr.us-west-1.amazonaws.com/order-svc:latest
          ports:
            - containerPort: 8080