package com.amazonaws.saas.eks.orderservice.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AtomicCounterExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

@Configuration
public class DynamoDbConfig {
    @Primary
    @Bean(name = "dynamoDbClient")
    public DynamoDbEnhancedClient dynamoDbEnhancedClient(@Value("${aws.region}") final String region) {
        DynamoDbClient ddb = DynamoDbClient.builder()
                .credentialsProvider(DefaultCredentialsProvider.create())
                .region(Region.of(region))
                .build();
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(ddb)
                .extensions(AtomicCounterExtension.builder().build(), AutoGeneratedTimestampRecordExtension.builder().build())
                .build();
    }
}