package com.amazonaws.saas.eks.orderservice.domain.model.customer;

import com.amazonaws.saas.eks.orderservice.domain.model.enums.EntityType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

import java.time.Instant;

@DynamoDbBean
@Data
public class Customer {
    public static final String TABLE = "ORDERS-OMN";
    private String entity = EntityType.CUSTOMER.getLabel();
    private String id;
    private String name;
    private String email;
    private String customerId;
    private Instant created;
    private Instant modified;

    @DynamoDbPartitionKey
    public String getEntity() {
        return entity;
    }

    @DynamoDbSortKey
    public String getId() {
        return id;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    public Instant getCreated() {
        return created;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getModified() {
        return modified;
    }
}
