name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-west-1
      - name: Build Docker image
        run: |
          docker build -t order-svc .

      - name: Tag Docker image
        run: |
          docker tag order-svc:latest 708224731803.dkr.ecr.us-west-1.amazonaws.com/order-svc:latest

      - name: Push Docker image to ECR
        run: |
          docker push 708224731803.dkr.ecr.us-west-1.amazonaws.com/order-svc:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job will run after the build job completes

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/order-service order-service=708224731803.dkr.ecr.us-west-1.amazonaws.com/order-svc:latest
